<?php

/**
 * @file
 * Provides widget hooks on behalf of geofield_droppin.
 */

/**
 * Implements hook_field_widget_info().
 */
function geofield_droppin_field_widget_info() {
  $widgets = array();

  $widgets['geofield_geofield_droppin'] = array(
    'label' => t('Drop Pin Map'),
    'field types' => array('geofield'),
  );

  return $widgets;
}

/**
 * Implements hook_field_widget_form().
 */

function geofield_droppin_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  geophp_load();
  
  if (!empty($items[$delta]['geom'])) {
    $geom = geoPHP::load($items[$delta]['geom']);
  }
  else {
    $geom = FALSE;
  }
  
  if ($geom) {
    $default_value = $geom->out('json');
  }
  else {
    $default_value = '';
  }
  
  $map_id = drupal_html_id('geofield-droppin-widget');
  $geom_id = drupal_html_id('geofield-droppin-widget-geom');

  $element['geom'] = array(
    '#type' => 'hidden',
    '#attributes' => array(
      'class' => array('geofield_wkt'),
      'id' => $geom_id,
    ),
    '#default_value' => $default_value,
    '#required' => (isset($instance['required'])) ? $instance['required'] : FALSE,
  );

  // Make sure we set the input-format to WKT so geofield knows how to process it
  $element['map'] = array(
    '#markup' => '<div id="'.$map_id.'" class="geofield-droppin-map" data-geom-id="'.$geom_id.'"></div>',
  );

  // Add JavaScript
  $element['#attached']['js'] = array(
    // External JS
    array(
      'data' => 'http://cdn.leafletjs.com/leaflet-0.4/leaflet.js', 
      'type' => 'external',
    ),
    array(
      'data' => 'http://maps.google.com/maps/api/js?v=3.2&sensor=false', 
      'type' => 'external',
    ),
    
    // Plugin JS
    array(
      'data' => drupal_get_path('module', 'geofield_droppin')  . '/libraries/leaflet-plugins/layer/tile/Google.js',
      'type' => 'file',
    ),
    array(
      'data' => drupal_get_path('module', 'geofield_droppin')  . '/libraries/Leaflet.zoomslider/src/L.Control.Zoomslider.js',
      'type' => 'file',
    ),
    
    // Local JS
    array(
      'data' => drupal_get_path('module', 'geofield_droppin')  . '/geofield_droppin.js',
      'type' => 'file',
    ),
  );
  
  // Add CSS
  $element['#attached']['css'] = array(
    // External CSS
    array(
      'data' => 'http://cdn.leafletjs.com/leaflet-0.4/leaflet.css', 
      'type' => 'external',
    ),
    
    // Plugin CSS
    array(
      'data' => drupal_get_path('module', 'geofield_droppin') . '/libraries/Leaflet.zoomslider/src/L.Control.Zoomslider.css',
      'type' => 'file',
    ),
    
    // Local CSS
    array(
      'data' => drupal_get_path('module', 'geofield_droppin') . '/geofield_droppin.css',
      'type' => 'file',
    ),
  );
  
  //@@TODO: Add IE CSS: http://cdn.leafletjs.com/leaflet-0.4/leaflet.ie.css  
  //@@TODO: Add IE CSS: /libraries/Leaflet.zoomslider/src/L.Control.Zoomslider.ie.css
  
  #drupal_add_js('http://cdn.leafletjs.com/leaflet-0.4/leaflet.js', 'external');
  #drupal_add_js('http://maps.google.com/maps/api/js?v=3.2&sensor=false', 'external');
  #drupal_add_css('http://cdn.leafletjs.com/leaflet-0.4/leaflet.css', 'external');


  // Add plugins
  #drupal_add_js(drupal_get_path('module', 'geofield_droppin')  . '/libraries/leaflet-plugins/layer/tile/Google.js');
  #drupal_add_js(drupal_get_path('module', 'geofield_droppin')  . '/libraries/Leaflet.zoomslider/src/L.Control.Zoomslider.js');
  #drupal_add_css(drupal_get_path('module', 'geofield_droppin') . '/libraries/Leaflet.zoomslider/src/L.Control.Zoomslider.css');


  // Add local JavaScript and CSS
  #drupal_add_js(drupal_get_path('module', 'geofield_droppin')  . '/geofield_droppin.js');
  #drupal_add_css(drupal_get_path('module', 'geofield_droppin') . '/geofield_droppin.css');

  return $element;
}
